all: testclient

testclient: testclient.o cli-out/ds2480sim.o cli-out/ds1963s.o cli-out/extern/crcutil.o cli-out/extern/sha1.o
	gcc -O0 -g3 $^ -o testclient

cli-out/extern:
	mkdir -p cli-out/extern

cli-out/%.o: %.c cli-out/extern
	gcc -c -O0 -g3 $< -o $@

%.o: %.c
	gcc -c -O0 -g3 $< -o $@

clean:
	rm -rf cli-out testclient testclient.o
