all: testclient

testclient: testclient.o cli-out/ds2480sim.o cli-out/ds1963s.o cli-out/crcutil.o cli-out/sha1.o
	gcc -O0 -g3 $^ -o testclient

cli-out:
	mkdir -p cli-out

cli-out/%.o: %.c cli-out
	gcc -c -O0 -g3 $< -o $@

%.o: %.c
	gcc -c -O0 -g3 $< -o $@

clean:
	rm -rf cli-out testclient testclient.o
